
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 123456
  host: localhost
  port: 5432
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: clinica_integra_development
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 123456
  host: localhost
  port: 5432
  

test:
  <<: *default
  database: clinica_integra_test
  username: postgres
  password: 123456
  host: localhost
  port: 5432


production:
  primary: &primary_production
    <<: *default
    database: clinica_integra_production
    username: clinica_integra
    password: <%= ENV["CLINICA_INTEGRA_DATABASE_PASSWORD"] %>
